meta:
  name: my-spring-app
  version: 4.0.0
  environment: jvm
  toolchain:
    name: maven
    version: 17

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RestApiHse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  company-service:
    build:
      context: ./company-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RestApiHse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    run:
      jarName: target/company-service.jar  # Убедитесь, что JAR-файл создается в этой папке
    commands:
      - mvn clean package  # Команда для сборки JAR-файла

  vacancy-service:
    build:
      context: ./vacancy-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/RestApiHse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
    run:
      jarName: target/vacancy-service.jar  # Убедитесь, что JAR-файл создается в этой папке
    commands:
      - mvn clean package  # Команда для сборки JAR-файла

  
volumes:
  postgres_data: