meta:
  environment: jvm
  toolchain:
    name: maven
    version: 17

build:
  artifacts:
    target/*.jar: /

services:
  vacancy-service:
    run:
      jarName: vacancy-service/target/vacancy-service.jar
      persistenceMount: /data
      containerPort: 80

  company-service:
    run:
      jarName: company-service/target/company-service.jar
      persistenceMount: /data
      containerPort: 80

  db:
    image: postgres:latest
    env:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432