name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: RestApiHse
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build company-service
      run: |
        cd company-service/demo
        mvn clean package
        
    - name: Build vacancy-service
      run: |
        cd vacancy-service/demo
        mvn clean package
    
    
    - name: Build Docker image
      run: |
        cd vacancy-service
        docker build -t ieatprettygirl/hse-rep .
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker images
      run: |
        cd vacancy-service
        docker push ieatprettygirl/hse-rep

    - name: Stop and remove services
      run: docker-compose down
