name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: RestApiHse
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
        ports:
          - 5433:5432

      pgadmin:
        image: dpage/pgadmin4
        env:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - 5051:80

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build company-service
      run: |
        cd company-service/demo
        mvn clean package

    - name: Build vacancy-service
      run: |
        cd vacancy-service/demo
        mvn clean package
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run services
      run: docker-compose up -d --build

    - name: Wait for services to be ready
      run: |
        sleep 30  # Дайте время для инициализации баз данных и сервисов

    - name: Stop and remove services
      run: docker-compose down
